title: DATA-FM Workshop @ ICLR 2025
description: Data Problem in Foundation Model Workshop @ ICLR 2025.

# Build settings
markdown: kramdown
include: ['_pages']

domain: datafm.github.io   # if you want to force HTTPS, specify the domain without the http at the start
url: https://datafm.github.io  # the base hostname and protocol for your site, e.g. https://example.com
